// Raw deal data transcribed from the firm's original "Deal Pipeline" spreadsheet
// export (Deal_Pipeline_08.14.26.xlsx). Used by prisma/seed.ts to populate a
// fresh database. Feel free to delete/edit these once real data is imported
// (see the in-app Excel import at /settings/import for re-importing updates).

export type RawDeal = {
  projectName: string | null;
  companyName: string | null;
  hq: string | null;
  description: string | null;
  website: string | null;
  stage: string;
  status: string;
  sourceName: string | null;
  referralType: string | null;
  primaryContactName: string | null;
  type: string | null;
  dateReceived: string;
  primaryIndustry: string | null;
  secondaryIndustry: string | null;
  enterpriseValue: number | null;
  revenue: number | null;
  ebitda: number | null;
  nextStep: string | null;
  primaryOwnerInitials: string | null;
  secondaryOwnerInitials: string | null;
  reasonForPass: string | null;
};

export const RAW_DEALS: RawDeal[] = [
  {
    projectName: "Project Brew",
    companyName: "Royal Cup",
    hq: "Birmingham, AL",
    description:
      "Major importer, roaster, and distributor of specialty coffees and fine teas since 1896, serving restaurants, hotels, offices, and retail nationwide.",
    website: "www.royalcupcoffee.com",
    stage: "7 - Closed",
    status: "Executed",
    sourceName: "Braemont Capital",
    referralType: "Sponsor",
    primaryContactName: "Herb May",
    type: "Equity Co-Invest",
    dateReceived: "2026-04-17",
    primaryIndustry: "Consumer",
    secondaryIndustry: "Food and Beverage",
    enterpriseValue: 270,
    revenue: 740,
    ebitda: 50,
    nextStep: "Execute docs and fund",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "BM",
    reasonForPass: null,
  },
  {
    projectName: null,
    companyName: "Welchel Towing",
    hq: "Marietta, GA",
    description:
      "Family-owned towing and recovery company operating multiple wrecker service brands (Marietta Wrecker, New Image Towing, Statewide Wrecker, Chancey's) across metro Atlanta.",
    website: "www.welchel.com",
    stage: "5 - LOI / Term Sheet Submitted",
    status: "Active",
    sourceName: "Practical Growth Advisors",
    referralType: "Investment Bank",
    primaryContactName: "John Coffin",
    type: "Minority Equity",
    dateReceived: "2026-04-06",
    primaryIndustry: "Infrastructure",
    secondaryIndustry: "Transportation and Logistics",
    enterpriseValue: 75,
    revenue: 44.5,
    ebitda: 9.6,
    nextStep: "Await feedback of submitted term sheet",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "BM",
    reasonForPass: null,
  },
  {
    projectName: null,
    companyName: "Crescent Wealth Advisory",
    hq: "Atlanta, GA",
    description:
      "Registered investment advisory firm providing asset management, family office, and insurance/sports consulting services to high-net-worth clients.",
    website: "www.crescentwealthadvisory.com",
    stage: "5 - LOI / Term Sheet Submitted",
    status: "Active",
    sourceName: null,
    referralType: "Proprietary",
    primaryContactName: null,
    type: "Control Buyout",
    dateReceived: "2025-10-31",
    primaryIndustry: "Financial Services",
    secondaryIndustry: "Insurance",
    enterpriseValue: 31.5,
    revenue: 7.5,
    ebitda: 4.5,
    nextStep: "Provide feedback on counter offer",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "BM",
    reasonForPass: null,
  },
  {
    projectName: null,
    companyName: "HYER",
    hq: "Olathe, KS",
    description:
      "Fifth-generation, family-owned western wear brand credited as an originator of the cowboy boot, selling handcrafted men's and women's boots and apparel.",
    website: "https://hyerboots.com",
    stage: "5 - LOI / Term Sheet Submitted",
    status: "Active",
    sourceName: null,
    referralType: "Firm Connection",
    primaryContactName: "Johnathan Rich",
    type: "Equity Co-Invest",
    dateReceived: "2026-06-02",
    primaryIndustry: "Consumer",
    secondaryIndustry: "Consumer Products",
    enterpriseValue: 65,
    revenue: 27.2,
    ebitda: -2.6,
    nextStep: "Pending terms from Silas",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "CH",
    reasonForPass: null,
  },
  {
    projectName: "Project Chalkboard",
    companyName: "Prime Wine & Spirits",
    hq: "Doraville, GA",
    description:
      "Boutique wine and spirits distributor serving retailers, restaurants, and suppliers throughout Georgia.",
    website: "www.primewineandspirits.com",
    stage: "2 - NDA Signed / Initial Review",
    status: "Active",
    sourceName: "Georgia Banking",
    referralType: "Sponsor",
    primaryContactName: "David Fischer",
    type: "Debt",
    dateReceived: "2026-07-30",
    primaryIndustry: "Consumer",
    secondaryIndustry: "Food and Beverage",
    enterpriseValue: 30.5,
    revenue: 42,
    ebitda: null,
    nextStep: "Collecting preliminary diligence materials / working through potential structure",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "CH",
    reasonForPass: null,
  },
  {
    projectName: null,
    companyName: "Intown Golf Club",
    hq: "Atlanta, GA",
    description:
      "Private social golf club offering TrackMan simulator bays, dining, and member events in an urban clubhouse setting.",
    website: "www.intowngolfclub.com",
    stage: "2 - NDA Signed / Initial Review",
    status: "Dead",
    sourceName: "Atlanta Ventures",
    referralType: "Firm Connection",
    primaryContactName: "Jon Birdsong",
    type: "Equity Co-Invest",
    dateReceived: "2026-07-21",
    primaryIndustry: "Consumer",
    secondaryIndustry: "Consumer Channels and Leisure",
    enterpriseValue: 100,
    revenue: 22,
    ebitda: 3.3,
    nextStep: null,
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "CH",
    reasonForPass:
      "- Seasonality w/ correlation to colder months (not playing golf outside)\n- Unit/payback economics (capital intensive to expand w/ long payback periods)\n- Capped cash flows on mature locations (~$2M peak)\n- Real estate heavy w/ lease risk\n- Consumer availability of golf simulators (wealthier customer base likely to buy)\n- Large deferred revenue component (slower cash cycles w/ booked dues, etc.)\n- Somewhat crowded, well-funded competitors (Five Iron Golf, X-Golf, GolfSuites, etc.)\n- Membership sales dependency (heavy initiation fees - if slow, then what?)",
  },
  {
    projectName: null,
    companyName: "Flock Safety",
    hq: "Atlanta, GA",
    description:
      "Public safety technology company making license plate readers, video cameras, drones, and gunshot detection tools used by law enforcement, businesses, and neighborhoods.",
    website: "www.flocksafety.com",
    stage: "2 - NDA Signed / Initial Review",
    status: "Dead",
    sourceName: "Vista",
    referralType: "Sponsor",
    primaryContactName: null,
    type: "Debt",
    dateReceived: "2026-07-21",
    primaryIndustry: "Technology",
    secondaryIndustry: "Cybersecurity",
    enterpriseValue: null,
    revenue: 337,
    ebitda: -148,
    nextStep: null,
    primaryOwnerInitials: "JG",
    secondaryOwnerInitials: "CH",
    reasonForPass:
      "- AI advances could allow competitors to erode Flock's market position\n- Revenue depends on municipal/law-enforcement budgets (political shifts/cuts)\n- Scaling installed base keeps CapEx/cash burn elevated\n- Growth relies on unit/logo expansion (minimal pricing or margin efficiency)\n- Debt facility has capped upside but bears downside risk of cash-burning business\n- ~9-year tenure w/ no view to financial stability (negative FCF in 2029E)\n- Backlog is thin relative to business's size w/ growth reliant on unconverted pipeline\n- Material miss/no momentum comp to org 2026E budget (-47%/-$42M cARR)\n- Regulatory red tape is a high hurdle\n- Vendor concentration: Primax is sole-source CM for all 4 core camera SKUs (~25% CapEx)",
  },
  {
    projectName: "Project Gala",
    companyName: "Glass Enterprises",
    hq: "Camilla, GA",
    description:
      "Leading U.S. producer of top-grade (Grade-1) alligator hides used in ultra-luxury goods sold by the world's most prominent fashion houses, including LVMH, Kering, Prada, Dior, Berluti, and Bottega Veneta.",
    website: null,
    stage: "2 - NDA Signed / Initial Review",
    status: "Dead",
    sourceName: "JP Morgan",
    referralType: "Investment Bank",
    primaryContactName: "David Alexander",
    type: "Control Buyout",
    dateReceived: "2026-06-25",
    primaryIndustry: "Consumer",
    secondaryIndustry: "Consumer Products",
    enterpriseValue: 275,
    revenue: 47,
    ebitda: 26,
    nextStep: null,
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "BM",
    reasonForPass:
      "- Biological/mortality risk inherent to live-animal operations\n- Customer concentration in a small set of ultra-luxury brands/tanneries\n- Exotic-skins policy risk (brand exits, activist/PR pressure)\n- 12-36 month grow-out cycle ties up working capital (~571 days inventory)\n- Regulatory dependence",
  },
  {
    projectName: null,
    companyName: "Johnson Paving",
    hq: "Blue Ridge, GA",
    description:
      "Asphalt paving, grading, and aggregate processing contractor serving subdivision, commercial, municipal, and residential projects across North Georgia.",
    website: "https://johnsonpavingco.com",
    stage: "2 - NDA Signed / Initial Review",
    status: "Active",
    sourceName: "Practical Growth Advisors",
    referralType: "Investment Bank",
    primaryContactName: "John Coffin",
    type: "Control Buyout",
    dateReceived: "2026-07-31",
    primaryIndustry: "Business Services",
    secondaryIndustry: "Engineering and Infrastructure",
    enterpriseValue: null,
    revenue: 24.7,
    ebitda: 5.5,
    nextStep: "Pending internal review",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "BM",
    reasonForPass: null,
  },
  {
    projectName: "Project Bluebird",
    companyName: "BridgeTower Media",
    hq: "Greensboro, NC",
    description:
      "Media company operating 40+ B2B news brands (legal, business journals, home furnishings, etc.) offering data, insights, and marketing/advertising solutions to industry executives.",
    website: "https://bridgetowermedia.com",
    stage: "2 - NDA Signed / Initial Review",
    status: "Active",
    sourceName: "Plangenix",
    referralType: "Sponsor",
    primaryContactName: "Ryan Kaplan",
    type: "Equity Co-Invest",
    dateReceived: "2026-07-13",
    primaryIndustry: "Business Services",
    secondaryIndustry: "Marketing Services",
    enterpriseValue: 85,
    revenue: 72.5,
    ebitda: 18.5,
    nextStep: "Pending internal review",
    primaryOwnerInitials: "BM",
    secondaryOwnerInitials: null,
    reasonForPass: null,
  },
  {
    projectName: "Project Oak",
    companyName: "Engineered Tower Solutions",
    hq: "Raleigh, NC",
    description:
      "Full-service engineering firm providing structural/geotechnical engineering, inspections, and construction for wireless communication towers and infrastructure nationwide.",
    website: "https://ets-pllc.com",
    stage: "2 - NDA Signed / Initial Review",
    status: "Active",
    sourceName: "Argonne Capital",
    referralType: "Sponsor",
    primaryContactName: "Bill Weimer",
    type: "Control Buyout",
    dateReceived: "2026-07-23",
    primaryIndustry: "Industrials",
    secondaryIndustry: "Advanced Manufacturing and Engineered Products",
    enterpriseValue: 50,
    revenue: 36.5,
    ebitda: 6.2,
    nextStep: "Pending internal review",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "BM",
    reasonForPass: null,
  },
  {
    projectName: null,
    companyName: "College Sports Co",
    hq: "Boston, MA",
    description:
      "Athlete-driven media and production company that builds content, shows, and brands connecting college athletes and university partners with fans.",
    website: "https://collegesportsco.com",
    stage: "2 - NDA Signed / Initial Review",
    status: "Active",
    sourceName: "Discerning Capital",
    referralType: "Sponsor",
    primaryContactName: "David Williams",
    type: "Equity Co-Invest",
    dateReceived: "2026-07-29",
    primaryIndustry: "Technology",
    secondaryIndustry: "Digital Media and Entertainment",
    enterpriseValue: 40,
    revenue: 12,
    ebitda: -2.2,
    nextStep: "Pending internal review",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "BM",
    reasonForPass: null,
  },
  {
    projectName: "Project Oasis",
    companyName: null,
    hq: "Mid-Atlantic",
    description:
      "Residential direct-to-consumer outdoor-living services platform that provides premium composite decks and adjacent products including screened porches, enclosures, patios, hardscapes, and under-deck waterproofing.",
    website: null,
    stage: "2 - NDA Signed / Initial Review",
    status: "Active",
    sourceName: "Blue Ridge Construction Capital",
    referralType: "Sponsor",
    primaryContactName: "Casey Rentch",
    type: "Equity Co-Invest",
    dateReceived: "2026-08-05",
    primaryIndustry: "Business Services",
    secondaryIndustry: "Facility and Residential Services",
    enterpriseValue: 24,
    revenue: 25,
    ebitda: 4,
    nextStep: "Pending internal review",
    primaryOwnerInitials: "JB",
    secondaryOwnerInitials: "CH",
    reasonForPass: null,
  },
];
